version: '3.2'

services:

  tomcat:
    image: 192.168.1.145:5000/mw:tfg
    #command:
    ports:
      - "8080:8080"
    networks:
      - traefik_proxy
      - postgres_default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mw.rule=Host(`mw.secandsys.com`)"
        - "traefik.http.routers.mw.entrypoints=web"
        - "traefik.http.services.mw.loadbalancer.server.port=8080" 
        - "traefik.http.routers.mw-secured.rule=Host(`mw.secandsys.com`)"
        - "traefik.http.routers.mw-secured.entrypoints=web-secured"
        - "traefik.http.routers.mw-secured.tls.certresolver=mytlschallenge"

networks:
  traefik_proxy:
    external: true
  
  postgres_default:
    external: true
