version: '3.2'

services:

  tomcat:
    image: 192.168.1.145:5000/mw:v0.1
    #command:
    ports:
      - "8080:8080"
    networks:
      - middleware
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  middleware:
    driver: overlay
    attachable: true
  dbnet:

